export const candidateDataBrowserHtml = `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TN Candidate Data Browser</title><style>
body{margin:0;font-family:system-ui,sans-serif;background:#071a36;color:#eaf3ff}main{max-width:1180px;margin:auto;padding:28px}h1{margin:0 0 8px}.bar{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;margin:24px 0}input,button{padding:12px;border-radius:8px;border:1px solid #5278aa;background:#0b2852;color:#fff}button{background:#1677ff;font-weight:700}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px}section{background:#0b2852;border:1px solid #264d7d;border-radius:12px;padding:16px;overflow:auto}pre{white-space:pre-wrap;word-break:break-word;font-size:12px}.warn{color:#ffd479}@media(max-width:760px){.bar{grid-template-columns:1fr}}
</style></head><body><main><h1>Talent Nexus Candidate Data Browser</h1><div>Internal debug view · ATS ID / TN code / UUID</div>
<div class="bar"><input id="id" placeholder="ATS Candidate ID，例如 43198"><input id="token" type="password" placeholder="TN internal bearer token（僅保留於本頁記憶體）"><button id="load">查詢</button></div><div id="status"></div><div class="grid" id="out"></div>
<script>
const labels={identity:'Identity',atsBaseline:'ATS Baseline',aiProfile:'AI Profile',evidence:'Evidence',processing:'Processing',warnings:'Data Quality / Warnings',rawAiSnapshot:'Raw AI Snapshot'};
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
document.getElementById('load').onclick=async()=>{const id=document.getElementById('id').value.trim(),token=document.getElementById('token').value;document.getElementById('status').textContent='Loading…';document.getElementById('out').innerHTML='';try{const r=await fetch('/internal/data-browser/candidates/'+encodeURIComponent(id),{headers:{Authorization:'Bearer '+token}});const body=await r.json();if(!r.ok)throw new Error(body?.error?.code||r.status);const d=body.data;document.getElementById('status').innerHTML='<h2>'+esc(d.header.name||'Unnamed')+' · ATS #'+esc(d.header.atsCandidateId||'—')+'</h2>';document.getElementById('out').innerHTML=Object.entries(labels).map(([k,v])=>'<section><h3>'+v+'</h3><pre class="'+(k==='warnings'?'warn':'')+'">'+esc(JSON.stringify(d[k],null,2))+'</pre></section>').join('')}catch(e){document.getElementById('status').textContent='Unable to load: '+e.message}};
</script></main></body></html>`;
