export const candidateDataBrowserHtml = `<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>TN Candidate Data Browser</title><style>
body{margin:0;font-family:system-ui,sans-serif;background:#071a36;color:#eaf3ff}main{max-width:1180px;margin:auto;padding:28px}h1{margin:0 0 8px}.bar{display:grid;grid-template-columns:1fr 1fr auto;gap:10px;margin:24px 0}input,button{padding:12px;border-radius:8px;border:1px solid #5278aa;background:#0b2852;color:#fff}button{background:#1677ff;font-weight:700;cursor:pointer}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 18px}.actions button{background:#155f91}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px}section{background:#0b2852;border:1px solid #264d7d;border-radius:12px;padding:16px;overflow:auto}pre{white-space:pre-wrap;word-break:break-word;font-size:12px}.warn{color:#ffd479}@media(max-width:760px){.bar{grid-template-columns:1fr}}
</style></head><body><main><h1>Talent Nexus Candidate Data Browser</h1><div>內部診斷工具，可用 ATS ID、TN code 或 UUID 查詢。</div>
<div class="bar"><input id="id" placeholder="ATS Candidate ID，例如 43198"><input id="token" type="password" placeholder="TN internal bearer token（不會儲存）"><button id="load">載入</button></div><div id="status"></div><div class="actions" id="actions" hidden><button data-op="reprocess_profile">重新處理</button><button data-op="rebuild_projection">重建 Projection</button><button id="retry">重試最近失敗工作</button></div><div class="grid" id="out"></div>
<script>
const labels={identity:'Identity',atsBaseline:'ATS Baseline',aiProfile:'AI Profile',evidence:'Evidence / Extraction',processing:'Processing Jobs / State',warnings:'Data Quality / Warnings',rawAiSnapshot:'Raw AI Snapshot'};
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));let loaded=null;
const auth=()=>({Authorization:'Bearer '+document.getElementById('token').value,'Content-Type':'application/json'});
async function load(){const id=document.getElementById('id').value.trim();document.getElementById('status').textContent='載入中…';document.getElementById('out').innerHTML='';document.getElementById('actions').hidden=true;try{const r=await fetch('/internal/data-browser/candidates/'+encodeURIComponent(id),{headers:auth()});const body=await r.json();if(!r.ok)throw new Error(body?.error?.code||r.status);loaded=body.data;document.getElementById('status').innerHTML='<h2>'+esc(loaded.header.name||'未命名')+' · ATS #'+esc(loaded.header.atsCandidateId||'—')+'</h2>';document.getElementById('out').innerHTML=Object.entries(labels).map(([k,v])=>'<section><h3>'+v+'</h3><pre class="'+(k==='warnings'?'warn':'')+'">'+esc(JSON.stringify(loaded[k],null,2))+'</pre></section>').join('');document.getElementById('actions').hidden=false}catch(e){document.getElementById('status').textContent='無法載入：'+e.message}}
async function action(operation){const id=document.getElementById('id').value.trim();const r=await fetch('/internal/data-browser/candidates/'+encodeURIComponent(id)+'/processing',{method:'POST',headers:auth(),body:JSON.stringify({operation})});const body=await r.json();if(!r.ok)throw new Error(body?.error?.code||r.status);document.getElementById('status').textContent='已排入處理工作：'+body.data.jobStatus;await load()}
document.getElementById('load').onclick=load;document.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>action(b.dataset.op).catch(e=>document.getElementById('status').textContent='無法排程：'+e.message));document.getElementById('retry').onclick=async()=>{try{const jobs=loaded?.processing?.jobs||[],latest=jobs.find(j=>['failed','needs_review','dead_letter'].includes(j.status));if(!latest)throw new Error('沒有可重試的工作');const r=await fetch('/internal/data-browser/processing/'+encodeURIComponent(latest.id)+'/retry',{method:'POST',headers:auth()});const body=await r.json();if(!r.ok)throw new Error(body?.error?.code||r.status);await load()}catch(e){document.getElementById('status').textContent='無法重試：'+e.message}};
</script></main></body></html>`;
